# Generated by Django 5.0.2 on 2024-03-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='url',
            new_name='link',
        ),
    ]
